#!/bin/bash
cd /home/ac1ssf/noisy-wsj-pf
. ./path.sh
( echo '#' Running on `hostname`
  echo '#' Started at `date`
  echo -n '# '; cat <<EOF
sum-tree-stats /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/1.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/10.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/11.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/12.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/13.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/14.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/15.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/16.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/17.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/18.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/19.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/2.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/20.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/21.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/22.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/23.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/24.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/25.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/26.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/27.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/28.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/29.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/3.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/30.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/31.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/32.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/4.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/5.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/6.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/7.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/8.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/9.treeacc 
EOF
) >/data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/log/sum_tree_acc.log
time1=`date +"%s"`
 ( sum-tree-stats /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/1.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/10.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/11.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/12.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/13.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/14.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/15.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/16.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/17.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/18.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/19.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/2.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/20.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/21.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/22.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/23.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/24.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/25.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/26.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/27.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/28.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/29.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/3.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/30.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/31.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/32.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/4.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/5.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/6.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/7.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/8.treeacc /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/9.treeacc  ) 2>>/data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/log/sum_tree_acc.log >>/data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/log/sum_tree_acc.log
ret=$?
time2=`date +"%s"`
echo '#' Accounting: time=$(($time2-$time1)) threads=1 >>/data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/log/sum_tree_acc.log
echo '#' Finished at `date` with status $ret >>/data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/log/sum_tree_acc.log
[ $ret -eq 137 ] && exit 100;
touch /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/q/done.80591
exit $[$ret ? 1 : 0]
## submitted with:
# qsub -S /bin/bash -v PATH -cwd -j y -o /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/q/sum_tree_acc.log -l rmem=6G   /data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/q/sum_tree_acc.sh >>/data/ac1ssf/noisy-wsj-pf/exp-noise/tri4a/q/sum_tree_acc.log 2>&1
